### PR TITLE
Oct3 progress update

### PR DESCRIPTION
**Pull request by kaiweih**
this is another thoughtful update, but we need to figure out how to do the "onClick" stuff...

### CODE REVIEW

**Review by chcho2 — APPROVED** [review]
good

**Review by alicejfu — APPROVED** [review]

**Review by chcho2 — APPROVED** [review]
good

**Review by ymturan — APPROVED** [review]

**Review by alicejfu — APPROVED** [review]
approve

**Review by alicejfu — APPROVED** [review]
please merge

**Review by ymturan — APPROVED** [review]

**Pull request merged**
